source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'Facebook-iOS-SDK'
pod 'SDWebImage'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'SWRevealViewController'
pod 'SplunkMint-iOS'
pod 'PBJVision'
pod 'DBPrivacyHelper'
pod 'SinchRTC'
pod 'TTTAttributedLabel'
pod 'NMRangeSlider'
pod 'ParseCrashReporting'
pod 'JSQMessagesViewController'